### ISSUE TITLE
Connection issue with Android demo project

### ISSUE THREAD

**Issue by yuehengshiCarmedia2p0** [ricohapi/theta-client#52]
Hi there, I'm running the Android demo, it works without issue for SC2, whereas there is a small problem after capturing with SC and going back to the preview page, sometimes it's freezing and sometimes it throws an error like the [video](https://youtu.be/eKL9z9XN7ds) shows.

The error is as follows
`E/ThetaViewModel$startPreview: com.ricoh360.thetaclient.PreviewClientException: Forbidden
        at com.ricoh360.thetaclient.PreviewClientImpl.responseStatus(PreviewClient.kt:367)
        at com.ricoh360.thetaclient.PreviewClientImpl.access$responseStatus(PreviewClient.kt:73)
        at com.ricoh360.thetaclient.PreviewClientImpl$responseStatus$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
`

Thanks in advance!!!

**Comment by simago** [comment]
@yuehengshiCarmedia2p0 Thank for the defect report.
I observed same error with Theta SC. I will investigate this issue.

**Comment by simago** [comment]
I have fixed this defect.  Please wait for the next release.
